#!/bin/bash

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# install core and development Python dependencies into the currently activated venv
function install {
    uv pip install --group dev
    uv pip install -e .
}

# run linting, formatting, and other static code quality tools during local development
function lint {
    pre-commit run --all-files
}

# same as `lint` but with any special considerations for CI
function lint:ci {
    # We skip no-commit-to-branch since that blocks commits to `main`.
    # All merged PRs are commits to `main` so this must be disabled.
    SKIP=no-commit-to-branch pre-commit run --all-files
}

# # execute tests that are not marked as `slow`
# function test:quick {
#     run-tests -m "not slow" ${@:-"$THIS_DIR/tests/"}
# }

# execute tests against the installed package; assumes the wheel is already installed
function test:ci {
    INSTALLED_PKG_DIR="$(python -c 'import {{ cookiecutter.project_slug }}; print({{ cookiecutter.project_slug }}.__path__[0])')"
    # in CI, we must calculate the coverage for the installed package, not the src/ folder
    COVERAGE_DIR="$INSTALLED_PKG_DIR" run-tests
}

# (example) ./run.sh test tests/test_states_info.py::test__slow_add
function run-tests {
    mkdir -p "$THIS_DIR/test-reports"
    PYTEST_EXIT_STATUS=0
    python -m pytest ${@:-"$THIS_DIR/tests/"} \
        --cov "${COVERAGE_DIR:-$THIS_DIR/src}" \
        --cov-report html \
        --cov-report term \
        --cov-report xml \
        --junit-xml "$THIS_DIR/test-reports/report.xml" || ((PYTEST_EXIT_STATUS+=$?))
    mv coverage.xml "$THIS_DIR/test-reports/" || true
    mv htmlcov "$THIS_DIR/test-reports/" || true
    mv .coverage "$THIS_DIR/test-reports/" || true
    return $PYTEST_EXIT_STATUS
}

function test:wheel-locally {
    deactivate 2>/dev/null || true
    rm -rf test-env 2>/dev/null || true
    uv venv test-env
    source test-env/bin/activate
    clean 2>/dev/null || true
    uv pip install build
    build
    uv pip install ./dist/*.whl pytest pytest-cov
    test:ci
    deactivate || true
    rm -rf test-env 2>/dev/null || true
}

# serve the html test coverage report on localhost:8000
function serve-coverage-report {
    uv run python -m http.server --directory "$THIS_DIR/test-reports/htmlcov/" 8000
}

# build a wheel and sdist from the Python source code
function build {
    uv  run python -m build --sdist --wheel "$THIS_DIR/"
}

# function release:test {
#     lint
#     clean
#     build
#     publish:test
# }

# function release:prod {
#     release:test
#     publish:prod
# }

# function publish:test {
#     try-load-dotenv || true
#     twine upload dist/* \
#         --repository testpypi \
#         --username=__token__ \
#         --password="$TEST_PYPI_TOKEN"
# }

# function publish:prod {
#     try-load-dotenv || true
#     twine upload dist/* \
#         --repository pypi \
#         --username=__token__ \
#         --password="$PROD_PYPI_TOKEN"
# }

# remove all files generated by tests, builds, or operating this codebase
function clean {
    rm -rf dist build coverage.xml test-reports .pytest_cache .ruff_cache .ty_cache .coverage || true
    find . \
      -type d \
      \( \
        -name "*cache*" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -exec rm -r {} + 2>/dev/null || true

    find . \
      -type f \
      -name "*.pyc" \
      -not -path "*/venv/*" \
      -not -path "*/test-env/*" \
      -exec rm -f {} + 2>/dev/null || true
}

# export the contents of .env as environment variables
function try-load-dotenv {
    if [ ! -f "$THIS_DIR/.env" ]; then
        echo "no .env file found"
        return 1
    fi

    set -o allexport
    source "$THIS_DIR/.env"
    set +o allexport
}

# print all functions in this file
function help {
    echo "Usage:$0 <task> <args>"
    echo "Available tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
