#!/bin/bash

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# install core and development Python dependencies into the currently activated venv
function install {
    uv pip install --group dev
    uv pip install cookiecutter
}

function generate-project {
    cookiecutter ./ \
    --output-dir "$THIS_DIR/template" 

    cd "$THIS_DIR/template"
    cd $(ls)
    git init
    git branch -M main
    git add --all
    git commit -m "feat: generated mlops python project scaffolding from cookiecutter template"
}

# remove all files generated by tests, builds, or operating this codebase
function clean {
    rm -rf dist build coverage.xml test-reports template/ || true
    find . \
      -type d \
      \( \
        -name "*cache*" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -exec rm -r {} + 2>/dev/null || true

    find . \
      -type f \
      -name "*.pyc" \
      -not -path "*/venv/*" \
      -not -path "*/test-env/*" \
      -exec rm -f {} + 2>/dev/null || true
}

# export the contents of .env as environment variables
function try-load-dotenv {
    if [ ! -f "$THIS_DIR/.env" ]; then
        echo "no .env file found"
        return 1
    fi

    set -o allexport
    source "$THIS_DIR/.env"
    set +o allexport
}

# print all functions in this file
function help {
    echo "Usage:$0 <task> <args>"
    echo "Available tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
