#!/bin/bash

set -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# install core and development Python dependencies into the currently activated venv
function install {
    uv pip install --upgrade pip
    uv pip install cookiecutter pytest pytest-xdist pre-commit
}

function lint:ci {
    # We skip no-commit-to-branch since that blocks commits to `main`.
    # All merged PRs are commits to `main` so this must be disabled.
    export PRE_COMMIT_HOME=~/.cache/pre-commit
    if [[ -n "$VIRTUAL_ENV" ]]; then
        export UV_PROJECT_ENVIRONMENT="$VIRTUAL_ENV"
        SKIP=no-commit-to-branch pre-commit run --all-files
    else
        SKIP=no-commit-to-branch uv run pre-commit run --all-files
    fi
}

#  run tests
function run-tests {
    python -m pytest ${@:-"$THIS_DIR/tests/"}
}

# generate a new project from this cookiecutter template
function generate-project {
    cookiecutter ./ \
    --output-dir "$THIS_DIR/template"

    cd "$THIS_DIR/template"
    cd $(ls)
    git init
    git branch -M main
    git add --all
    git commit -m "feat: generated mlops python project scaffolding from cookiecutter template"
}

# remove all files generated by tests, builds, or operating this codebase
function clean {
    rm -rf dist build coverage.xml test-reports template/ || true
    find . \
      -type d \
      \( \
        -name "*cache*" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -exec rm -r {} + 2>/dev/null || true

    find . \
      -type f \
      -name "*.pyc" \
      -not -path "*/venv/*" \
      -not -path "*/test-env/*" \
      -exec rm -f {} + 2>/dev/null || true
}

# export the contents of .env as environment variables
function try-load-dotenv {
    if [ ! -f "$THIS_DIR/.env" ]; then
        echo "no .env file found"
        return 1
    fi

    set -o allexport
    source "$THIS_DIR/.env"
    set +o allexport
}

function configure_git_credentials {
    if [[ -z "${GH_TOKEN:-}" ]]; then
        echo "GH_TOKEN is required for authenticated Git operations" >&2
        return 1
    fi
}

function configure_git_remote {
    git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO_NAME}.git"
}

function create_repo_if_not_exists {
    local IS_REPO_PUBLIC=${IS_REPO_PUBLIC:-false}

    # check if the repo already exists
    echo "Checking if repo $GITHUB_USERNAME/$GITHUB_REPO_NAME exists"
    if gh repo view "$GITHUB_USERNAME/$GITHUB_REPO_NAME" > /dev/null 2>&1; then
        echo "Repo $GITHUB_USERNAME/$GITHUB_REPO_NAME already exists"
        return 0
    fi

    echo "Repo $GITHUB_USERNAME/$GITHUB_REPO_NAME does not exist, creating it now"
    if [[ "$IS_REPO_PUBLIC" == "true" ]]; then
        echo "Creating public repo"
        gh repo create "$GITHUB_USERNAME/$GITHUB_REPO_NAME" --public

    else
        echo "Creating private repo"
        gh repo create "$GITHUB_USERNAME/$GITHUB_REPO_NAME" --private

    fi

    push_initial_readme_to_repo

}

function push_initial_readme_to_repo {

    configure_git_credentials

    # delete the repo clone if it already exists
    if [[ -d "$GITHUB_REPO_NAME" ]]; then
        echo "Deleting existing repo clone $GITHUB_REPO_NAME"
        rm -rf "$GITHUB_REPO_NAME"
    fi

    # clone the repo and cd into it
    gh repo view "$GITHUB_USERNAME/$GITHUB_REPO_NAME" > /dev/null
    gh repo clone "$GITHUB_USERNAME/$GITHUB_REPO_NAME"
    cd "$GITHUB_REPO_NAME"
    configure_git_remote

    # create a README.md file with the repo name
    echo "# $GITHUB_REPO_NAME" > README.md


    # add the README.md file to the repo, commit to main branch, and push to the remote repo
    git add README.md
    git commit -m "feat: created repository"
    git branch -M main
    git push -u origin main

}


function open_pr_with_generated_project {

    # install dependencies if not already installed
    install
    configure_git_credentials

    # remove the repo clone and outdir if it already exists
    OUTDIR="template"

    if [[ -d "$GITHUB_REPO_NAME" ]]; then
        echo "Deleting existing repo clone $GITHUB_REPO_NAME"
        rm -rf "$GITHUB_REPO_NAME"
    fi

    if [[ -d "$OUTDIR" ]]; then
        echo "Deleting existing template directory $OUTDIR"
        rm -rf "$OUTDIR"
    fi

    # clone the repo
    gh repo view "$GITHUB_USERNAME/$GITHUB_REPO_NAME" > /dev/null
    gh repo clone "$GITHUB_USERNAME/$GITHUB_REPO_NAME"
    cd "$GITHUB_REPO_NAME"
    configure_git_remote
    cd ..

    # delete the contents of cloned repo preserving only the .git directory
    mv "$GITHUB_REPO_NAME/.git" "./$GITHUB_REPO_NAME.git-backup"
    rm -rf "$GITHUB_REPO_NAME"
    mkdir "$GITHUB_REPO_NAME"
    mv "./$GITHUB_REPO_NAME.git-backup" "$GITHUB_REPO_NAME/.git"

    # run cookiecutter to generate the project template and move the .git directory to the generated project
    echo "Generating cookiecutter config json file"
    CONFIG_FILE_PATH="./$GITHUB_REPO_NAME.config.yaml"
    PROJECT_SLUG="${GITHUB_REPO_NAME,,}"
    PROJECT_SLUG="${PROJECT_SLUG// /}"
    PROJECT_SLUG="${PROJECT_SLUG//-/_}"
    cat <<EOF > "$CONFIG_FILE_PATH"
default_context:
    project_name: $GITHUB_REPO_NAME
    project_slug: $PROJECT_SLUG
    project_description: ${GITHUB_REPO_DESCRIPTION:-"Production MLOps pipeline template with automated CI/CD"}
    author_name: ${USER_FULLNAME:-$GITHUB_USERNAME}
    author_github_handle: $GITHUB_USERNAME
EOF

    if [[ -f "$CONFIG_FILE_PATH" ]]; then
        echo "Config file $CONFIG_FILE_PATH created successfully"
    else
        echo "Failed to create config file $CONFIG_FILE_PATH"
        exit 1
    fi

    echo "Generating project from cookiecutter template"
    cookiecutter ./ --output-dir "$OUTDIR" \
    --no-input \
    --config-file "$CONFIG_FILE_PATH"
    rm "$CONFIG_FILE_PATH"

    # check if the generated project directory exists
    if [[ ! -d "$OUTDIR/$PROJECT_SLUG" ]]; then
        echo "Generated project directory $OUTDIR/$PROJECT_SLUG does not exist"
        exit 1
    fi

    # create a new branch, add all files, run linting once, re-stage, commit, and push to the remote repo
    echo "Creating new branch, adding all files, running linting, re-staging, committing, and pushing to the remote repo"
    mv "$GITHUB_REPO_NAME/.git" "$OUTDIR/$PROJECT_SLUG/"
    cd "$OUTDIR/$PROJECT_SLUG"

    UUID=$(cat /proc/sys/kernel/random/uuid)
    UNIQUE_BRANCH_NAME=populate-from-template-${UUID:0:6}

    git checkout -b "$UNIQUE_BRANCH_NAME"
    git add .

    # apply formatting and linting autofixes to the generated files
    lint:ci || true

    # re-stage all files after linting autofixes
    git add .

    # commit the changes and push to the remote repo
    echo "Committing and pushing to the remote repo"
    git commit -m "feat: generated mlops python project scaffolding from cookiecutter"

    git push -u origin "$UNIQUE_BRANCH_NAME"


    # open a pull request from the new branch to main
    echo "Opening a pull request from "$UNIQUE_BRANCH_NAME" to main"
    gh pr create \
        --title "feat: populated from \`python-course-cookiecutter-v2\` template" \
        --body "This PR was generated by \`python-course-cookiecutter-v2\`" \
        --base main \
        --head "$UNIQUE_BRANCH_NAME" \
        --repo "$GITHUB_USERNAME/$GITHUB_REPO_NAME"

}

function configure_repo {

    # Push AWS Secrets to the GitHub Actions secrets store
    if [[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_SECRET_ACCESS_KEY" && -n "$AWS_DEFAULT_REGION" ]]; then
        echo "Pushing AWS Secrets to the GitHub Actions secrets store"
        gh secret set AWS_ACCESS_KEY_ID \
        --body "$AWS_ACCESS_KEY_ID" \
        --repo "$GITHUB_USERNAME/$GITHUB_REPO_NAME"
        gh secret set AWS_SECRET_ACCESS_KEY \
            --body "$AWS_SECRET_ACCESS_KEY" \
            --repo "$GITHUB_USERNAME/$GITHUB_REPO_NAME"
        gh secret set AWS_DEFAULT_REGION \
            --body "$AWS_DEFAULT_REGION" \
            --repo "$GITHUB_USERNAME/$GITHUB_REPO_NAME"
    else
        echo "AWS Secrets are not set, skipping pushing to the GitHub Actions secrets store"
    fi



    # protect main branch, enforcing passing build on feature branch before merge
    BRANCH_NAME="main"
    gh api \
    --method PUT \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2026-03-10" \
    "repos/$GITHUB_USERNAME/$GITHUB_REPO_NAME/branches/$BRANCH_NAME/protection" \
    --input - <<EOF > /dev/null
{
  "required_status_checks": {
    "strict": true,
    "checks": [
      { "context": "Lint, Format, and other static code quality checks" },
      { "context": "Execute tests" },
      { "context": "Validate Version & Check Tag Conflict" },
      { "context": "Test building wheel locally" }
    ]
  },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "required_approving_review_count": 0
  },
  "restrictions": null
}
EOF

}

function create-sample-repo {
    git add .github/ run.sh \
    && git commit -m "fix: debugging the create-or-update-repo.yaml workflow" \
    && git push origin main || true

    gh workflow run .github/workflows/create-or-update-repo.yaml \
        -f repo_name=generated-repo-$REPO_NUMBER \
        -f package_import_name=generated_repo_$REPO_NUMBER \
        -f is_public_repo=false \
        --ref main
}

# print all functions in this file
function help {
    echo "Usage:$0 <task> <args>"
    echo "Available tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
