name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-format-and-static-code-checks:
    name: Lint, Format, and other static code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.11.29"

      - name: Install dependencies
        run: |
          uv venv .venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          /bin/bash -x run.sh install

      # - name: Install pre-commit
      #   run: uv pip install --system pre-commit

      - name: Lint, Format, and other static code quality checks
        run: /bin/bash -x run.sh lint:ci

  execute-tests:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Configure git CLI
        run: |
          git config --global user.email "7979807+ArunSubramanian456@users.noreply.github.com"
          git config --global user.name "Arun Subramanian"

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.11.29"

      - name: Install dependencies
        run: |
          uv venv .venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          /bin/bash -x run.sh install

      - name: Run Unit Tests and report coverage
        run: /bin/bash -x run.sh run-tests

  check-version-tag:
    name: Tag release version
    needs: [lint-format-and-static-code-checks, execute-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Tag with the release version
        run: |
          git tag $(cat version.txt)

  push-tags:
    name: Publish git tag
    needs:
      [lint-format-and-static-code-checks, execute-tests, check-version-tag]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Push tags
        run: |
          git push origin --tags

  # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
  dump-contexts-to-log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '{% raw %}${{ toJSON(github) }}{% endraw %}'
      - name: Dump job context
        run: echo '{% raw %}${{ toJSON(job) }}{% endraw %}'
      - name: Dump steps context
        run: echo '{% raw %}${{ toJSON(steps) }}{% endraw %}'
      - name: Dump runner context
        run: echo '{% raw %}${{ toJSON(runner) }}{% endraw %}'
      - name: Dump strategy context
        run: echo '{% raw %}${{ toJSON(strategy) }}{% endraw %}'
      - name: Dump matrix context
        run: echo '{% raw %}${{ toJSON(matrix) }}{% endraw %}'
      - name: Dump secrets
        run: echo '{% raw %}${{ toJSON(secrets) }}{% endraw %}'
      - name: Dump vars
        run: echo '{% raw %}${{ toJSON(vars) }}{% endraw %}'
